---
title: "Lab 00 - Hello IDS!"
author: "HANNAH RAE"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Tim", "Sue", "Kate", 
           "Simon", "Sophie"),
  github_username = c("mcgregors-garden", "craftytangent", "hrae9", 
                      "silenteclipse", "sponge2"), 
  colour = c("powderblue", "purple", "yellow", 
             "green", "red"),
  hobby = c("Hopping", "gaming", "football", 
            "shopping", "cooking"),
  favourite_number = c(2, 3, 4, 5, 6)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

bar chart of users by GitHub username against their favourite number filled in by their favourite colour


